In [1]:
### Tutorial from Defend Intelligence youtube channel

## NUMPY

import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [20]:
#np.arange
print(np.arange(10))
print()
print(np.arange(9).reshape(3,3))
print()
print(np.arange(8).reshape(4,2))
print()
print(np.arange(8).reshape(2,4))

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 1 2 3]
 [4 5 6 7]]


In [19]:
## zeros, ones, eyes
print(np.zeros((3,2)))
print()
print(np.ones((4,6)))
print()
print(np.eye(3,2))

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [23]:
## random
print(np.random.rand(5))
print()
print(np.random.random(size=(3,2)))

[0.38348355 0.90493834 0.88509962 0.5885233  0.59604584]

[[0.10063735 0.51275918]
 [0.8026747  0.58009974]
 [0.20824211 0.98120101]]


In [39]:
## indexing

myArray = np.random.rand(5)
print(myArray)
print(type(myArray))
print(myArray[3])
print()
print()

myArray_multidimension = np.random.rand(6).reshape(3,2)
print(myArray_multidimension)
print()
print(myArray_multidimension[0,0])
print()
print(myArray_multidimension[0:,0]) # all values of the 1st column 
print()
print(myArray_multidimension[0:,1]) # all values of the 2nd column


[0.78739706 0.89160413 0.16918699 0.48831302 0.29502909]
<class 'numpy.ndarray'>
0.4883130156594664


[[0.28307986 0.3465024 ]
 [0.24446491 0.53164607]
 [0.91215686 0.86853124]]

0.28307986484458847

[0.28307986 0.24446491 0.91215686]

[0.3465024  0.53164607 0.86853124]
